# Disable all metrics.
Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Prefer compact module/class defs
Style/ClassAndModuleChildren:
  Enabled: false

# Allow CamelCase constants as well as SCREAMING_SNAKE_CASE
Style/ConstantName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
  
# Allow 'Pokémon-style' exception handling
Lint/RescueException:
  Enabled: false

# Prefer |m, e| for the `reduce` block arguments
Style/SingleLineBlockParams:
  Methods:
    - reduce: [m, e]
    - inject: [m, e]

AllCops:
  TargetRubyVersion: 2.4.1

# http://stackoverflow.com/questions/4763121/should-i-use-alias-or-alias-method
Style/Alias:
  Enabled: false

# So RuboCop doesn't complain about application IDs
Style/NumericLiterals:
  Exclude:
    - examples/*

# So RuboCop doesn't complain about EndOfLine errors that don't even exist
EndOfLine:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/LineLength:
  Max: 100