source 'https://rubygems.org'
gem 'discordrb', git: 'https://github.com/meew0/discordrb.git',
                 branch: 'master'
gem 'dotenv'
gem 'easy_translate'
gem 'rufus-scheduler'
gem 'sequel'
gem 'sqlite3'
gem 'time_difference'
gem 'titleize'
